name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      # Checks out your repository code so your workflow can access it.

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Caches npm dependencies to speed up subsequent runs.

    - name: Install dependencies
      run: npm ci
      # `npm ci` is used for clean installations in CI environments, ensuring reproducible builds.

    - name: Build project (if build script exists)
      run: npm run build --if-present
      # Runs the 'build' script if defined in package.json.

    - name: Run tests
      run: npm test
      # Executes your project's tests.

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # Your Codecov token. Ensure this is stored as a repository secret.
        # file: ./coverage.xml # Uncomment and modify if your coverage report is not automatically found.
        # flags: unittests # Optional flags to differentiate coverage reports.
        # name: ci-coverage # Optional custom name for the Codecov run.
